### PR TITLE
Move to GitHub actions

### PR DESCRIPTION
**Pull request by Muscraft**
This PR adds a GitHub actions workflow that is similar to what was being done for Travis CI and removes things related to Travis CI.

### CODE REVIEW

**Comment by sfackler** [comment]
Nice! Do we need to yolo merge this to get the first build kicked off? I can't remember how GH actions bootstraps.

**Comment by Muscraft** [comment]
According to [their docs (at the bottom of the section)](https://docs.github.com/en/actions/quickstart#creating-your-first-workflow), it runs after it's committed:

> Committing the workflow file to a branch in your repository triggers the push event and runs your workflow.

I am not sure why it didn't, so I went and copied what was done in [rust-lang/annotate-snippets-rs](https://github.com/rust-lang/annotate-snippets-rs/blob/ff0c5502df8418e5f2a14225ddc446f87e5a91c4/.github/workflows/ci.yml#L3C1-L10).

**Comment by Muscraft** [comment]
Looks like merging the PR made [actions start working](https://github.com/rust-lang/docker-rust/actions/runs/7359828548)!

**Comment by sfackler** [comment]
🎊 https://github.com/rust-lang/docker-rust/actions/runs/7359828548

**Pull request merged**
