### PR TITLE
fix: Move alpine3.19 to correct directory

### PR DESCRIPTION
**Pull request by Muscraft**
When #166 was merged before #168 and #168 was not rebased on top of #166, it caused `alpine3.19` to be in the wrong directory and left artifacts of `alpine3.17`. This PR moves `alpine3.19` to the correct directory (`1.75.0`) and removes the `alpine3.17` directory.

### CODE REVIEW

**Comment by sfackler** [comment]
I think https://github.com/rust-lang/docker-rust/commit/e7f8ab58b3feca354792122f4df6624e291c404b should have fixed that?

**Comment by sfackler** [comment]
Oh but the 3.17 image was still there

**Comment by Muscraft** [comment]
Whoops, I must've not gotten that commit when I merged things, either way `3.17` is still there

**Comment by Muscraft** [comment]
Whoops sent this after you merged, Thanks!

**Pull request merged**
