### PR TITLE
Update to 1.57.0

### PR DESCRIPTION
**Pull request by sksat**

### CODE REVIEW

**Comment by sfackler** [comment]
https://github.com/docker-library/official-images/pull/11441

**Comment by sksat** [comment]
@sfackler thank you!
However, it looks like empty tags are being pushed. Is this a problem with the official-images (build pipeline)?
I think our two PRs are fine.

https://hub.docker.com/_/rust?tab=tags&page=1&name=1.57
image

**Comment by sfackler** [comment]
The official image CI pipeline can take some time to run - it may not have finished yet.

**Comment by sksat** [comment]
I was wondering if it wouldn't be tagged unless at least one image was pushed. I will wait patiently.

**Comment by sfackler** [comment]
Update on missing tags: https://github.com/docker-library/official-images/pull/11441#issuecomment-985814851

**Pull request merged**
