### PR TITLE
Added Alpine 3.15 support

### LINKED ISSUE #93: Alpine 3.15
Similar to #86, but for Alpine 3.15 :)

### PR DESCRIPTION
**Pull request by Razican**
This closes #93.

### CODE REVIEW

**Comment by sfackler** [comment]
LGTM other than removing 3.13!

**Comment by sfackler** [comment]
Thanks!

**Comment by Razican** [comment]
> Thanks!

Thanks for the merge! should a PR be created in the official-images repo? Is this done automatically?

**Comment by sfackler** [comment]
This'll get picked up with the next Rust release.

**Pull request merged**
