### PR TITLE
Add beta images

### LINKED ISSUE #13: Docker hub image hasn't been updated.
Even though the manifest is bumped to 1.22, the dockerhub repo is stuck at the 1.21 version.

### LINKED ISSUE #14: Provide beta images
It would be nice to have an official repository of up-to-date Rust beta images, to complete the rustup-like trifecta for automated CI runs and the like.

### PR DESCRIPTION
**Pull request by sfackler**
Closes #14

### CODE REVIEW

**Comment by sfackler** [comment]
@alexcrichton Is there a rustup channel for each specific beta release?

**Comment by alexcrichton** [comment]
Not currently, no

**Comment by sfackler** [comment]
Is that kind of thing handled by CI or manually? Would it be doable to have a channel per beta?

**Comment by alexcrichton** [comment]
Hm I'm not sure what you mean? You can install a specific beta using `beta-yyyy-mm-dd` but why would we have a channel per beta?

**Comment by sfackler** [comment]
I'm asking about supporting `rustup update 1.23.0-beta.1` in addition to `rustup update 1.23.0`.

**Comment by alexcrichton** [comment]
Technically it should be feasible (along with everything else) but does the beta date not work?

**Comment by sfackler** [comment]
That should work I think - it's just a tiny bit less clear that the right beta's getting picked up.

**Comment by beatgammit** [comment]
Any updates on this? I'd like to use the beta builds if possible. :)

**Comment by sdroege** [comment]
This sounds very useful, it would allow running CI with beta too to basically give free pre-release testing in addition to running on nightly and stable :)

**Comment by sfackler** [comment]
Now that we make beta releases automatically whenever a commit lands on the branch, I think we'd probably need some automation here to support beta docker images.

**Comment by TimDiekmann** [comment]
I wrote something about automation in #14 . If desired, I can make a PR out of it that replaces this one.

**Pull request closed without merging**
